src/sparsetensors/quantization/__init__.py, src/sparsetensors/quantization/quant_args.py, src/sparsetensors/quantization/quant_config.py, src/sparsetensors/quantization/quant_scheme.py, tests/quantization/test_quant_args.py, tests/quantization/test_quant_config.py, tests/quantization/test_quant_scheme.py
Design doc: https://docs.google.com/document/d/1p74N_XzTeEITK2ldWmeVXzZ8JbiYITHG2rcPg0bE0Vs/edit
=> Define BaseModels for Quantization

src/sparsetensors/quantization/__init__.py, src/sparsetensors/quantization/apply.py, src/sparsetensors/quantization/lifecycle/__init__.py, src/sparsetensors/quantization/lifecycle/apply.py, src/sparsetensors/quantization/lifecycle/calibration.py, src/sparsetensors/quantization/lifecycle/forward.py, src/sparsetensors/quantization/lifecycle/frozen.py, src/sparsetensors/quantization/lifecycle/initialize.py, src/sparsetensors/quantization/quant_config.py, tests/__init__.py, tests/quantization/__init__.py, tests/quantization/lifecycle/__init__.py, tests/quantization/lifecycle/test_apply.py
adds support for applying relevant portions of the quantization lifecycle in-order to a model from a quant config
includes refactoring of quantization status to deduplicate implementations and add an ordering mechanism
**test_plan:**
test included for quantizing a tinyllama model
test does not currently include running a forward pass
=> Apply quantization config implementation

src/sparsetensors/quantization/__init__.py, src/sparsetensors/quantization/observers/memoryless.py, src/sparsetensors/quantization/observers/min_max.py
fixes issues with:
* asymmetric zero points not typed to int
* min/max observer should not include the 0 safety bound in its running average
* init file update
=> fix observer bugs

src/sparsetensors/quantization/lifecycle/apply.py, src/sparsetensors/quantization/lifecycle/calibration.py, src/sparsetensors/quantization/lifecycle/frozen.py, src/sparsetensors/quantization/lifecycle/initialize.py
docstrings and a ux update for the quantization lifecycle
cleans up usage a bit to make support for `torch.apply` with the lifecycle a first class citizen
=> [lifecycle] docstrings + ux update to work with torch.apply

src/sparsetensors/quantization/observers/__init__.py, src/sparsetensors/quantization/observers/helpers.py, src/sparsetensors/quantization/observers/memoryless.py, src/sparsetensors/quantization/observers/min_max.py
**test_plan**:
tested against PTQ example (#10)
=> [Observers] pull shared logic into a helper function

src/compressed_tensors/quantization/observers/helpers.py, src/compressed_tensors/quantization/observers/memoryless.py, src/compressed_tensors/quantization/observers/min_max.py
A few change so we match pytorch quantization more closely:
* Adding averaging constant and renaming MinMaxObserver to MovingAverageMinMaxObserver
* using torch.aminmax to calculate mins and maxes in observer. (This fixed some errors we had against the pytorch quantization, I'm really not sure why)
* slight implementation changes in scale/zp calculation
Before these changes we were consistently seeing a 10-15% drop in perplexity compared to pytorch quantization. Now we are matching them within 2% and aren't consistently worse. We still don't have exact matching of scale/zeropoint calculations but I'm chalking that up to C++ vs Python differences (some of the pytorch quantization is implemented in c++)
perplexity test is in: https://github.com/neuralmagic/sparseml/pull/2246
=> Quantization Fixes

README.md, setup.py, src/compressed_tensors/compressors/__init__.py, src/compressed_tensors/compressors/base.py, src/compressed_tensors/compressors/dense.py, src/compressed_tensors/compressors/helpers.py, src/compressed_tensors/compressors/sparse_bitmask.py
Changing the helper `infer_compressor_from_model_config` to `ModelCompressor.from_pretrained` to match more closely with `QuantizationConfig.from_pretrained`
Also adding a device default to decompress to fix some errors in the sparseml tests
=> [Release 0.3.2] Additional patches to enable compatibility with SparseML, UX changes

src/compressed_tensors/quantization/lifecycle/forward.py, src/compressed_tensors/quantization/observers/base.py, src/compressed_tensors/quantization/observers/helpers.py, src/compressed_tensors/quantization/observers/min_max.py
Addresses the following:
* torch API usage updates to limit allocation of new memory
* vectorized implementation of min/max observer for channel wise / group size
* fixes correctness bug with min/max observer where channelwise/group splits would override the same shared average min and max values
**test_plan:**
tested against PTQ script locally, confirmed significant speedups
=> group size speedups + fixes

src/compressed_tensors/quantization/lifecycle/forward.py
Fixing an issue where `device_map="auto"` would not work with the new quantization framework
=> Fix for auto device map quantization

src/compressed_tensors/quantization/lifecycle/forward.py, src/compressed_tensors/quantization/observers/base.py, src/compressed_tensors/quantization/observers/memoryless.py, src/compressed_tensors/quantization/observers/min_max.py, tests/test_quantization/test_configs/test_strategies.py
We had vectorized the scale and zeropoint calculations for the minmax observer, but the memoryless observer was still using the un-vectorized code. Moved the `get_qparams_along_dim` to the base observer class so all observers use it, and resolved some shape issues. 
With this change the token,channel and tensor strategies can all use the same logic for calling quant/dequant so this simplified the forward pass code a lot too
Running a llama1.1b model with w8a8 dynamic per token:
Before change: 10 sec/iteration
After change: 4.5 iterations/sec
A huge speedup!
=> Fix per_token slowdown

src/compressed_tensors/quantization/quant_scheme.py
This PR adds a class method in QuantizationScheme, to load a default scheme; this is needed for PR https://github.com/neuralmagic/sparseml/pull/2263
=> [GPTQ Modifier UX] Add default scheme

src/compressed_tensors/compressors/int_quantized.py, src/compressed_tensors/compressors/pack_quantized.py, tests/test_compressors/test_int_quant.py, tests/test_compressors/test_pack_quant.py
Requested by @dsikka, including the zero point in the state dict when the quantization is symmetric complicates the loading process in vLLM. On the compressed-tensors side, we now only save the zero point to the state_dict if it contains non-zeros (not symmetric). On reload in SparseML, the zero_point tensor will be recreated during decompression
Updated unit tests for the compressors to ensure the zero_point is removed from the state_dict in symmetric mode. The reload unit test already confirms we correctly recreate the zero_point during decompression
=> Remove Symmetric Zero Point in Compressed Outputs

src/compressed_tensors/quantization/lifecycle/forward.py, tests/test_compressors/test_int_quant.py
Fixing two issues that came up during testing for grouped decompression:
* scale/zp dimmension had changed from 3 to 2, updating tests and strategy inference code accordingly
* weight dtype was changing from what model was initialized with during fake_quantization. Updated forward pass to always use the dtype of the original weight during fake_quant
=> Fixed Grouped Quantization Reload

README.md, examples/bit_packing/ex_quantize_and_pack.py, examples/bitmask_compression.ipynb, examples/llama_1.1b/ex_config_quantization.py, examples/llama_1.1b/ex_sparseml_quantization.py, examples/quantize_and_pack_int4.ipynb, src/compressed_tensors/README.md, tests/test_quantization/lifecycle/test_apply.py, tests/test_quantization/lifecycle/test_dynamic_lifecycle.py, tests/test_utils/test_helpers.py
Loading models with `AutoModelForCausalLM` or `SparseAutoModelForCausalLM` without explicitly specifying `torch_dtype="auto"` loads the weights into `fp32` and ignores `torch_dtype` entry from `config.json`. This is the default behavior of HF-transformers which we want to override so that conversion to compressed-tensors preserves the dtype of the original model.
=> Fix incorrect loading of dtype

.github/workflows/build-test-publish-nightly.yaml
- The runner is using a different timezone. Update cronjob to match the expected 6pm time
=> Update time for the runner

setup.py
Allow any future versions of transformers since we are just using it for `AutoConfig` at the moment and would like to support new models.
=> Remove version restriction on transformers

src/compressed_tensors/quantization/observers/base.py, tests/test_quantization/test_configs/test_strategies.py
* Fix bug where the input of observed.shape = [batch, token, hidden] lead to output of [1, ... ...], instead of [batch,...,...]
=> reduce appropriate dim

src/compressed_tensors/compressors/__init__.py, src/compressed_tensors/compressors/marlin_24.py, src/compressed_tensors/compressors/model_compressor.py, src/compressed_tensors/compressors/utils/__init__.py, src/compressed_tensors/compressors/utils/helpers.py, src/compressed_tensors/compressors/utils/permutations_24.py, src/compressed_tensors/compressors/utils/semi_structured_conversions.py, src/compressed_tensors/config/base.py, src/compressed_tensors/utils/safetensors_load.py, tests/test_compressors/test_marlin_24.py
Implements Marlin24 compression in SparseML. Note that this compressor does not have a decompress method, it is meant only for feeding directly into vllm.
Since this is a one-way conversion for vLLM, we won't automatically convert to this format when `save_compressed` is set in SparseML. Instead the save will have to be done explicitly like this:
```
from sparseml.transformers import SparseAutoModelForCausalLM, SparseAutoTokenizer
import torch
model_dir = "/network/sadkins/llama7b_sparse_24_w4a16_group128"
output_dir = "llama7b_marlin24"
model = SparseAutoModelForCausalLM.from_pretrained(model_dir, torch_dtype=torch.float16, device_map="cuda")
tokenizer = SparseAutoTokenizer.from_pretrained(model_dir)
model.save_pretrained(output_dir, quantization_format="marlin-24") …
```
=> Marlin24 Compressor

src/compressed_tensors/compressors/base.py, src/compressed_tensors/compressors/marlin_24.py, src/compressed_tensors/compressors/model_compressor.py, src/compressed_tensors/compressors/naive_quantized.py, src/compressed_tensors/compressors/pack_quantized.py, src/compressed_tensors/quantization/lifecycle/apply.py, src/compressed_tensors/utils/helpers.py, tests/test_compressors/test_fp8_quant.py, tests/test_compressors/test_int_quant.py, tests/test_compressors/test_pack_quant.py
- Add the ability to pack int8 tensors into int32 packed weights
- This will allow the w8a16 models to run with the gpt_marlin kernels in vllm 
- Tested using the following recipe/script
```python
import torch
from sparseml.transformers import SparseAutoModelForCausalLM, oneshot
recipe = """
quant_stage:
quant_modifiers:
GPTQModifier:
sequential_update: false
ignore: ["lm_head"]
config_groups:
group_0:
weights:
num_bits: 8
type: "int"
symmetric: true
strategy: "channel"
targets: ["Linear"]
"""
model_stub = "TinyLlama/TinyLlama-1.1B-intermediate-step-1431k-3T"
model = SparseAutoModelForCausalLM.from_pretrained(
model_stub, torch_dtype=torch.bfloat16, device_map="auto"
)
dataset = "ultrachat-200k"
output_dir = "./output_llama1b_w8a16_channel_compressed"
splits = {"calibration": …
```
=> [compressor] Add packed int8 support

src/compressed_tensors/compressors/dense.py, src/compressed_tensors/compressors/marlin_24.py, src/compressed_tensors/compressors/naive_quantized.py, src/compressed_tensors/compressors/sparse_bitmask.py, src/compressed_tensors/quantization/quant_scheme.py
decompress was failing for non-packed models after adding the `name_to_scheme` arg. Adding a kwargs field to all the decompressors fixed the issue
=> Fix Decompress kwargs

src/compressed_tensors/compressors/model_compressor.py
This code:
```python
from compressed_tensors import ModelCompressor
compressor = ModelCompressor.from_pretrained("microsoft/Phi-3-mini-128k-instruct",trust_remote_code=True)
```
Failed before:
```bash
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/root/compressed-tensors/.venv/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 983, in from_pretrained
return config_class.from_dict(config_dict, **unused_kwargs)
File "/root/compressed-tensors/.venv/lib/python3.10/site-packages/transformers/configuration_utils.py", line 772, in from_dict
config = cls(**config_dict)
File "/root/compressed-tensors/.venv/lib/python3.10/site-packages/transformers/models/phi3/configuration_phi3.py", line 158, in __init__ …
```
=> Allow creating compressor when `trust_remote_code=True`

src/compressed_tensors/quantization/quant_scheme.py, tests/test_quantization/test_quant_config.py
* Default W8A8 to channelwise weights, dynamic per token activations
* Add new W8A16 preset
* Show all quantization args explicitly rather than assuming defaults for readability
=> Update Quantization Presets

src/compressed_tensors/quantization/quant_scheme.py
Enhances the quantization module by expanding the quantization schemes, inline docs, and default values to improve readability and usability.
- Added new quantization schemes for 4-bit weights and 8-bit activations (W4A8) and improved documentation for existing schemes.
- Updated the QuantizationArgs to include comprehensive default values.
- Added docs throughout to clarify the code
- Manual review
- Current automated tests
=> Update Quantization Scheme Standards for better readability

src/compressed_tensors/quantization/lifecycle/__init__.py, src/compressed_tensors/quantization/lifecycle/enable.py, src/compressed_tensors/quantization/lifecycle/forward.py, src/compressed_tensors/quantization/lifecycle/helpers.py, tests/test_quantization/lifecycle/test_enabled.py
adds `enable_quantization` and `disable_quantization`, which modifies a layer's new `quantization_enabled` property. if set to False, then no overrides of the forward pass will be in affect when running.  In practices applying this to a model `model.apply(disable_quantization)` reverts the model to its original run state.
also adds a small helper function that updates a layer's weight scale and zero point based on the current weight values
practical use of this will be for llm-compressor implemetation of GPTQ which requires pre-initialization of scales and zero points but should not use these values during initial hessian calibration
quantization is by default enabled
unit test included
@Satrat note that this will be incompatible with run_compressed (although not a compatibility that …
=> quatization lifecycle - disable forward pass override + helper for weight quant param updates

src/compressed_tensors/quantization/quant_scheme.py
Introduces a new FP8 dynamic quantization scheme for the latest Llama 3.1 models from Meta and addresses an issue with the W4A8 representation by setting dynamic token level for activations.
- FP8 Dynamic Scheme: Added a new FP8 dynamic quantization scheme to support the latest Llama3.1 models. This scheme applies dynamic quantization to the input activations.
- W4A8 Representation Fix: Fixed an issue with the W4A8 representation by changing the strategy for activations to dynamic, ensuring more accurate quantization.
- Comprehensive tests to be added for these schemes at a later date
- Falling back on current CI to ensure nothing is broken
=> Add FP8 Dynamic Scheme for Latest Llama3.1 Meta Models and Fix W4A8 Representation

src/compressed_tensors/utils/offload.py
This helper fn was failing when a non-leaf module was passed in. Adding a second case to return the correct execution device when the weights of the module are on the meta device. Required for https://github.com/vllm-project/llm-compressor/pull/47 to work with device offloading
=> Fix Execution Device Helper Fn

src/compressed_tensors/quantization/lifecycle/apply.py
In the examples like `examples/bit_packing/ex_quantize_and_pack.py` we call the `apply_quantization_config`. It changes in-place its config argument by adding `kv_cache` quantization group to the quantization group dictionary. This is desirable for the general logic, but should not be applied to the original `config` object, since it will be further appended to the model's `config.json`
=> Do not mutate config by `apply_quantization_config`

examples/bit_packing/int4_config.json, examples/llama_1.1b/example_quant_config.json, src/compressed_tensors/quantization/quant_config.py, tests/test_compressors/test_model_compressor.py, tests/test_quantization/lifecycle/test_dynamic_lifecycle.py, tests/test_quantization/lifecycle/test_kv_cache.py
For HfQuantizer compatibility. We don't use the `quantization_method` attribute anywhere in our codebase, so this change didn't break any examples or tests
=> Rename Quant Method

src/compressed_tensors/quantization/lifecycle/apply.py, src/compressed_tensors/quantization/lifecycle/calibration.py
When loading an already quantized model, we step through the sequence of quantization stages: `intiailized -> calibration -> frozen`. When setting modules to the calibration stage, we were recalculating the weight scale and zero point. This computation isn't needed, as the scale/zp get loaded in from the state_dict. This calculation should only happen if our end state is calibration.
Adding an additional argument that turns off weight calculations when loading in a frozen model to fix the issue. Confirmed this bypasses the computation in a manual test, and all the llm-compressor tests still pass
(We should get this in for the release, as this ends up being costly for large models)
=> Bug Fix for Calibration Setup

src/compressed_tensors/quantization/lifecycle/apply.py, src/compressed_tensors/quantization/lifecycle/calibration.py, tests/test_quantization/lifecycle/test_apply.py
Fix for https://github.com/neuralmagic/compressed-tensors/issues/112
Bug:
```
When I try to use regular expression in the "ignore" field of GPTQModifier it fails to recognize the appropriate models.
Example:
ignore: ["lm_head", “re:.*gate”]
Mixtral-7x8B-Instruct-v0.1
Some layers that were to be ignored were not found in the model: {'re:.*gate'}
```
The logic properly ignores the regex matches. The log raises because the logic to check if the regex was ignored was incorrect. PR fixes this bug.
Note: If not ignored, the module will have ` module.quantization_scheme`
=> Fix Issue #112

tests/test_quantization/lifecycle/test_apply.py
Followup to https://github.com/neuralmagic/compressed-tensors/pull/126,
previous test do not check if the warning was raised properly with respect to pytest
=> follow up, better tests

src/compressed_tensors/quantization/observers/__init__.py, src/compressed_tensors/quantization/observers/helpers.py, src/compressed_tensors/quantization/observers/mse.py, src/compressed_tensors/quantization/quant_args.py, src/compressed_tensors/utils/semi_structured_conversions.py, tests/test_quantization/test_observers/test_mse.py
This PR adds support for utilizing MSE for identifying clipping values for min-max quantization. The implemented was tested for different types of quantization - group-wise, channel-wise and tensor-wise using the following script:
```
from transformers import AutoTokenizer
from llmcompressor.transformers import SparseAutoModelForCausalLM, oneshot
from llmcompressor.modifiers.quantization import GPTQModifier
from compressed_tensors.quantization import QuantizationArgs, QuantizationScheme
from datasets import load_dataset
import random
model_id = "microsoft/Phi-3-mini-4k-instruct"
num_samples = 512
max_seq_len = 4096
tokenizer = AutoTokenizer.from_pretrained(model_id)
preprocess_fn = lambda example: {"text": "Below is an instruction that describes a task. Write a response that appropriately …
```
=> Adding MSE Clipping Support

src/compressed_tensors/compressors/model_compressor.py
Temporary fix to the serialized checkpoint format for quantized kv cache scales. 
The current issue is that storing the scales directly on the output of Linear modules doesn’t exactly match up the its usage in attention implementation. In vLLM the kv scales are members of the Attention class, rather than its Linear submodules. So rather than `model.layers.0.self_attn.k_proj.output_scale` we should use `model.layers.0.self_attn.k_scale`
Example script used to talk about differences in this PR:
```python
from llmcompressor.transformers import oneshot
recipe = """
quant_stage:
quant_modifiers:
QuantizationModifier:
kv_cache_scheme:
num_bits: 8
type: float
strategy: tensor
dynamic: false
symmetric: true
"""
oneshot(
model="TinyLlama/TinyLlama-1.1B-Chat-v1.0",
dataset="open_platypus", …
```
=> Move kv cache scales from k/v_proj.output_scale to self_attn.k/v_scale

src/compressed_tensors/quantization/lifecycle/forward.py, src/compressed_tensors/quantization/lifecycle/helpers.py, tests/test_quantization/lifecycle/test_forward.py, tests/test_quantization/lifecycle/test_helpers.py
This PR is a precursor to #97 which adds support for out-of-order group quantization specified by `g_idx`.
* Weights are permuted before and after quantization to account for new group quantization parameters
* Note that some datatypes such as `torch.float8_e4m3fn` do not implement `index_put_` and therefore must be permuted manually (this also prohibits group masking implementations
* `g_idx` is passed to quantization operations
The group quantization cases tested are
1. in-order group quantization, which is the case which has already been implemented
2. out-of-order group quantization with dtypes which support index_put_ operations
3. out-of-order group quantization with dtypes which do not support index_put_ operations
A follow-up PR could explore the potential performance/code …
=> Group Index Quantization Support

src/compressed_tensors/quantization/lifecycle/forward.py, src/compressed_tensors/quantization/lifecycle/helpers.py, src/compressed_tensors/quantization/observers/base.py, src/compressed_tensors/quantization/observers/helpers.py, src/compressed_tensors/quantization/observers/min_max.py, src/compressed_tensors/quantization/observers/mse.py, src/compressed_tensors/utils/__init__.py, src/compressed_tensors/utils/permute.py, tests/test_quantization/lifecycle/test_helpers.py
* Move the `safe_permute` to utils for easier access by #97 
* Add arguments to `update_layer_weight_quant_params` for use by #97
* Implement `reset` method on observers (will be tested in #97)
=> Move safe_permute, update layer helper arguments

src/compressed_tensors/quantization/lifecycle/helpers.py
Fixes mistake where g_idx was passed to the observer prior to that argument being implemented. Will be implemented in #97
=> Remove g_idx arg on observer

src/compressed_tensors/compressors/model_compressor.py, src/compressed_tensors/quantization/quant_scheme.py, src/compressed_tensors/quantization/utils/helpers.py
I wanted the ability to make calibrated kv cache scales without needing to quantize the weights or activations of any layers. There were some issues when making a QuantizationModifier without any inputs or weights QuantizationSchemes.
Here is the minimal recipe example I used for testing. It is still a bit verbose, so I would like to eventually reduce it to just the `kv_cache_scheme`:
```python
from llmcompressor.transformers import oneshot
recipe = """
quant_stage:
quant_modifiers:
QuantizationModifier:
config_groups:
group_0:
targets: []
kv_cache_scheme:
num_bits: 8
type: float
strategy: tensor
dynamic: false
symmetric: true
"""
oneshot(
model="TinyLlama/TinyLlama-1.1B-Chat-v1.0",
dataset="open_platypus",
recipe=recipe,
output_dir="TinyLlama-1.1B-Chat-v1.0-KV", …
```
=> Support quantizing only the kv cache

src/compressed_tensors/quantization/lifecycle/forward.py
Pass in updated scale or zp.
Fixed off by one error - Previously, the params gets registered by the module and will use that instead of the updated.
=> [Forward Call] fake quant fix

src/compressed_tensors/compressors/base.py, src/compressed_tensors/quantization/lifecycle/initialize.py, src/compressed_tensors/quantization/quant_args.py, tests/test_compressors/test_pack_quant.py, tests/test_quantization/test_quant_args.py
* Precursor to https://github.com/vllm-project/llm-compressor/pull/121
* Add additional activation ordering strategies
* Preserve use of booleans as arguments
* Fix bug with weight_g_idx compression
* Use ActivationOrderingStrategy type to validate actorder argument
* Default to weight-only activation ordering
* Use field validators to cast to enum types, move validator to after field_validators
* Modify/add tests for new activation orderings
* Added/modified unit tests
* Tested e2e with https://github.com/vllm-project/llm-compressor/pull/121 (see tests)
=> Activation Ordering Strategies

src/compressed_tensors/config/base.py
First in a set of PRs to make compressors composable.
This PR: Adds targets and ignore lists to `SparsityCompressionConfig` and is needed for 
https://github.com/vllm-project/llm-compressor/pull/191
Note this PR doesn't actually do anything with the targets/ignore lists, just updates the sparsity compression config to accept these args
=> Add: targets and ignore to sparsity compression config

src/compressed_tensors/quantization/quant_scheme.py
I think it is a bit strange to assume W8A8 is INT8, so added an alias to be explicit
=> Make INT8 activation PRESET_SCHEMES explicit

src/compressed_tensors/__init__.py, src/compressed_tensors/compressors/model_compressor.py
Adds a new `"version": "0.6.0.20240921"` entry to the `"compression_config": {` entry
Example compression config on an FP8 Dynamic Llama 3.1 8B:
```yaml
"compression_config": {
"config_groups": {
"group_0": {
"input_activations": {
"actorder": null,
"block_structure": null,
"dynamic": true,
"group_size": null,
"num_bits": 8,
"observer": "memoryless",
"observer_kwargs": {},
"strategy": "token",
"symmetric": true,
"type": "float"
},
"output_activations": null,
"targets": [
"Linear"
],
"weights": {
"actorder": null,
"block_structure": null,
"dynamic": false,
"group_size": null,
"num_bits": 8,
"observer": "minmax",
"observer_kwargs": {},
"strategy": "channel",
"symmetric": true,
"type": "float"
}
}
},
"format": "float-quantized",
"global_compression_ratio": 1.239290831149584,
"ignore": [ …
```
=> Write the current version into model configs

src/compressed_tensors/compressors/model_compressor.py
Previously, a no-operation (no-op) dense compression 
configuration was being used as the sparsity_config for  sparse-quantized models
However, since we do not yet support sparse compression for sparse-quantized models, the sparsity_config should ideally be left empty. This PR addresses that by ensuring the sparsity_config remains empty until sparse compression support is implemented for sparse-quantized models
Before this PR the compression_config from config.json was:
```json
"compression_config": {
"config_groups": {
"group_0": {
"input_activations": null,
"output_activations": null,
"targets": [
"Linear"
],
"weights": {
"actorder": null,
"block_structure": null,
"dynamic": false,
"group_size": 128,
"num_bits": 4,
"observer": "minmax",
"observer_kwargs": {},
"strategy": "group", …
```
=> Ignore Dense sparsity config

src/compressed_tensors/compressors/model_compressor.py
- Updates to swap out the `compression_config` key for `quantization_config`
- This will allow us to leverage `HFQuantizer` support and the `AutoModelForCausalLM` pathway
- Models can still be loaded through the `SparseAutoModelForCausalLM` pathway as well
- Old models (with the `compression_config` key) will still work through the `SparseAutoModelForCausalLM` pathway
```yaml
{
"_name_or_path": "/home/dsikka/.cache/huggingface/hub/models--TinyLlama--TinyLlama-1.1B-Chat-v1.0/snapshots/fe8a4ea1ffedaf415f4da2f062534de366a451e6",
"architectures": [
"LlamaForCausalLM"
],
"attention_bias": false,
"attention_dropout": 0.0,
"bos_token_id": 1,
"eos_token_id": 2,
"head_dim": 64,
"hidden_act": "silu",
"hidden_size": 2048,
"initializer_range": 0.02,
"intermediate_size": 5632, …
```
=> Replace `compression_config` to be `quantization_config` for `HFQuantizer` support

src/compressed_tensors/quantization/quant_config.py
Include "Linear" in the ignore list if only running to get the scales for kv-cache. 
right now quantization_type_names = {"...Attention..."}
before:
"ignore": [],
"kv_cache_scheme": {
"actorder": null,
"block_structure": null,
"dynamic": false,
"group_size": null,
"num_bits": 8,
"observer": "minmax",
"observer_kwargs": {},
"strategy": "tensor",
"symmetric": true,
"type": "float"
},
after:
"ignore": [
"model.layers.0.self_attn.q_proj",
"model.layers.0.self_attn.k_proj",
"model.layers.0.self_attn.v_proj",
"model.layers.0.self_attn.o_proj",
"model.layers.0.mlp.gate_proj",
"model.layers.0.mlp.up_proj",
"model.layers.0.mlp.down_proj",
"model.layers.1.self_attn.q_proj",
"model.layers.1.self_attn.k_proj",
"model.layers.1.self_attn.v_proj",
"model.layers.1.self_attn.o_proj", …
=> ignore list

.github/workflows/build-test.yml, .github/workflows/trigger-all.yml, .github/workflows/upload.yml, src/compressed_tensors/version.py
Fix nightly issue with HF code:
1. switched default build type to release
2. disabled pushing out to nm-pypi and public pypi for now until the issue is fixed from HF side.
=> switch default to release and disable pushing to pypi for now

src/compressed_tensors/compressors/__init__.py, src/compressed_tensors/compressors/base.py, src/compressed_tensors/compressors/base_quantization_compressor.py, src/compressed_tensors/compressors/base_sparsity_compressor.py, src/compressed_tensors/compressors/dense.py, src/compressed_tensors/compressors/helpers.py, src/compressed_tensors/compressors/marlin_24.py, src/compressed_tensors/compressors/model_compressor.py, src/compressed_tensors/compressors/naive_quantized.py, src/compressed_tensors/compressors/pack_quantized.py, src/compressed_tensors/compressors/sparse_bitmask.py, src/compressed_tensors/linear/compressed_linear.py, tests/test_compressors/test_marlin_24.py, tests/test_compressors/test_model_compressor.py, tests/test_quantization/test_quant_scheme.py, tests/test_registry.py
This PR represents the first PR towards making compressors composable.
It does two things:
Testing: All existing unit tests pass
This PR implements Part 1 from Design Document https://www.notion.so/Design-Document-24-Compressor-25ac643aee604c298f2bb12a6c220861?pvs=4
Existing Flow (before this PR)
Refactored (after this PR)
=> Add: base sparsity/quantization compressors

src/compressed_tensors/quantization/lifecycle/helpers.py
This function was originally used by llm-compressor's gptq, but is now no longer needed
=> Remove unused function

src/compressed_tensors/compressors/model_compressors/model_compressor.py
This reverts commit 6ed94e66a84af5f0ed2238bf61776f8c41653515.
This commit is causing downstream failures such as: 
```
FAILED tests/llmcompressor/transformers/finetune/test_oneshot_and_finetune.py::TestOneshotAndFinetuneGPU_0_nightly::test_oneshot_then_finetune_gpu - TypeError: 'NoneType' object is not subscriptable
```
=> Revert "Ignore Dense sparsity config (#169)"

src/compressed_tensors/quantization/lifecycle/apply.py
`CompressedTensorsHfQuantizer` attempts to use `apply_quantization_config` to apply the quantization config to the model
```python3
def _process_model_before_weight_loading(self, model, **kwargs):
from compressed_tensors.quantization import apply_quantization_config
ct_quantization_config = self.compressor.quantization_config
apply_quantization_config(model, ct_quantization_config, run_compressed=True)
```
However, `self.compressor.quantization_config` can be `None` in the case that only sparsity is present. This does not align with the function contract of `apply_quantization_config`. In such a case, an error is thrown.
```python3
def apply_quantization_config(
model: Module, config: QuantizationConfig, run_compressed: bool = False
) -> Dict:
```
This PR adjusts the function to handle …
=> Workaround HF Quantizer `apply_quantization_config` misuse

src/compressed_tensors/quantization/observers/mse.py, tests/test_quantization/test_observers/test_mse.py
This PR fixes the pre-allocation of a few tensors used in the MSE observer. The original allocation did not specify the device, which ended up leading to failures due to computation with tensors in different devices.
=> Fix device allocation for MSE observer

.github/workflows/trigger-all.yml
To drop python 3.8 in testing, and add 3.12.
=> drop 3.8 and add 3.12 to testing

src/compressed_tensors/quantization/lifecycle/calibration.py
* Fix calibration of offloaded models
* Previously, g_idx was being fetched before the module was onloaded, meaning that it was being fetch as a meta tensor
* Now g_idx is fetched after the module parameters are onloaded
* @anmarques was able to compress an offloaded model using activation ordering
=> [Bugfix] Move observer and g_idx until after module in onloaded

src/compressed_tensors/quantization/quant_args.py, src/compressed_tensors/registry/registry.py
* Better error message when attempting to load an unregistered class instance
* Avoid annoying users with configs which have observer=memoryless for dynamic quantization
* Clean up observer defaulting logic
* Return the type name in the case that it is not found in the list of aliases
* Condition warning on if observer != memoryless
```python3
from llmcompressor.observers import Observer
Observer.load_from_registry("asdf", quantization_args=None)
```
```
- KeyError: "Unable to find None registered under type <class 'llmcompressor.observers.base.Observer'>.\nRegistered values for <class 'llmcompressor.observers.base.Observer'>: ['minmax', 'mse']\nRegistered aliases for <class 'llmcompressor.observers.base.Observer'>: []"
+ KeyError: "Unable to find asdf registered under type <class …
```
=> Clean up observer defaulting logic, better error message

src/compressed_tensors/compressors/sparse_quantized_compressors/marlin_24.py
Summary
- Fix the check for permutations which have been incorrectly been running for the channel-wise case
- Idk how this ever worked for group quant
Generations Using Group Quantization in vLLM:
```bash
[' Paris and it is located in the north-west of the country.\nThe population of', ' the leader of the executive branch of the federal government, and thus the head of', ' Liz. I live in a small town in the middle of a prairie.']
```
=> [BugFix] Fix Marlin24 Bug

tests/test_quantization/lifecycle/test_apply.py, tests/testing_utils.py
* Better user experience for users who run
```bash
python3 -m pip install -e .
python3 -m pytest tests
```
* Skip tests which require accelerate if accelerate is not installed
* CI tests
=> Skip accelerate tests

src/compressed_tensors/quantization/quant_scheme.py, tests/test_quantization/test_quant_scheme.py
* Remove unused function. I believe that this function was initially intended to provide defaults to QuantizationModifier while not overwriting existing configs, but since all these values are all written to configs and the  QuantizationModifier is now also the default for configs which do not specify values, this function is no longer necessary.
* https://github.com/vllm-project/llm-compressor/pull/889
* Remove QuantizationScheme.default_scheme
* Grepped codebases for uses
=> Remove QuantizationScheme.default_scheme

src/compressed_tensors/compressors/base.py, src/compressed_tensors/compressors/model_compressors/model_compressor.py, src/compressed_tensors/linear/compressed_linear.py, src/compressed_tensors/quantization/lifecycle/apply.py, src/compressed_tensors/quantization/quant_config.py
Fix bugs on loading the compression_config to quantization_config. Loading from the former is now removed
Added minor doc string and type checks for confusing output from functions
=> Allow ModelCompressor.from_pretrained to load from quantization_config, not compression config

src/compressed_tensors/quantization/quant_scheme.py
* Make `QuantizationScheme` more user friendly by adding model validation
* This PR is only meant to guard against a few cases I encountered which were not explicitly covered downstream, so feel free to suggest any other invalid combinations we want to guard against.
* Add model validator to `QuantizationScheme`
=> Quantization Scheme Validation

src/compressed_tensors/compressors/quantized_compressors/naive_quantized.py, src/compressed_tensors/compressors/quantized_compressors/pack_quantized.py
Both compressors have a `can_quantize()` check, which if ever doesn't succeed would trigger:
> UnboundLocalError: cannot access local variable 'quantized_weight' where it is not associated with a value
Add the obvious fix for this and highly artificial test cases that would trigger it.
Looks like this error was introduced by #109
Definitely begs the question whether this code path has any real world use!
=> Fix uninitialized variable in quantized compressors

src/compressed_tensors/quantization/quant_args.py, src/compressed_tensors/quantization/quant_scheme.py, src/compressed_tensors/utils/helpers.py, tests/test_quantization/test_quant_args.py
* Add aliases for activation ordering options to improve usability for researchers familiar with autogptq
* Implement `AliasableEnum` mixin which allows enums to be aliased
* Add `AliasableEnum` to `ActivationOrdering` with the following map:
```python3
{
"dynamic": "group",
"static": "weight",
}
```
* Added passing tests in `tests/test_quantization/test_quant_args.py`
* Successfully quantized a model using `dynamic` actorder and tested e2e with vllm
<details><summary>llama3.py</summary>
```python3
from accelerate import cpu_offload
from datasets import load_dataset
from transformers import AutoModelForCausalLM, AutoTokenizer
from llmcompressor.modifiers.quantization import GPTQModifier
from llmcompressor.transformers import oneshot
MODEL_ID = "meta-llama/Llama-3.2-1B-Instruct"
model = …
```
=> Implement aliasable mixin and alias activation ordering

src/compressed_tensors/quantization/quant_args.py, src/compressed_tensors/quantization/quant_scheme.py, src/compressed_tensors/utils/helpers.py, tests/test_quantization/test_quant_args.py
* Add aliases for activation ordering options to improve usability for researchers familiar with autogptq
* Update previous #213 to support python<=3.9
* Implement `AliasableEnum` mixin which allows enums to be aliased
* Add `AliasableEnum` to `ActivationOrdering` with the following map:
```python3
{
"dynamic": "group",
"static": "weight",
}
```
* Remove the `@property` decorator from aliases to avoid interactions in python<=3.9 https://bugs.python.org/issue43682
* Added passing tests in `tests/test_quantization/test_quant_args.py`
* Successfully quantized a model using `dynamic` actorder and tested e2e with vllm
* Tested the above using python3.9
<details><summary>llama3.py</summary>
```python3
from accelerate import cpu_offload
from datasets import load_dataset
from transformers import …
```
=> Implement aliasable mixin and alias activation ordering (python3.9 fix)

src/compressed_tensors/quantization/lifecycle/initialize.py, src/compressed_tensors/utils/offload.py, tests/test_quantization/lifecycle/test_initialize.py, tests/test_utils/test_offload.py
* Add more utilities not covered by #193
* Add tests for offloading functions
* Reduce code complexity by using utility functions
* Fix bug in `update_offload_data` and expand capabilities
* Implement `align_module_device`, which has already been upstreamed and is just copied here until we bump the required `accelerate` version
* Implement `disable_hf_hook` and utilize in `initialize_module_for_quantization`
* Note that the previous "dictionary recreation" logic is no longer needed. It was previously necessary since the newly attached parameters were not updated in the state dict, however this is now done by `register_offload_parameter`
* Fix bug in `update_offload_data` where data would not be updated properly if the module was offloaded and weights_map dataset was being improperly …
=> Accelerate Utilities Follow-up

src/compressed_tensors/compressors/model_compressors/model_compressor.py, src/compressed_tensors/quantization/quant_config.py, tests/test_compressors/model_compressors/test_model_compressor.py, tests/test_quantization/lifecycle/test_apply.py, tests/test_quantization/lifecycle/test_dynamic_lifecycle.py, tests/test_quantization/test_quant_config.py
* Squelch pydantic depreciation warnings
* Replace all instances of `dict` with `model_dump`
* Replace all instances of `parse_obj` with `model_validate`
* Added test in `tests/test_quantization/test_quant_config.py`
```bash
grep -r '\.dict' src tests examples/
grep -r '\.parse_obj' src tests examples/
```
=> Replace depreciated pydantic functions

src/compressed_tensors/quantization/lifecycle/initialize.py, tests/conftest.py, tests/test_quantization/lifecycle/test_initialize.py, tests/test_quantization/test_configs/test_strategies.py, tests/test_quantization/test_utils/test_helpers.py
* While implementing #193, a bug was discovered where the shape of per-token scales is being initialized with the incorrect shape
* Change shape of initialized quantization parameters in per token case
* Unrelated, compare tuples rather than lists in `tests/test_quantization/test_configs/test_strategies.py`
* Added new tests in `tests/test_quantization/lifecycle/test_initialize.py`
=> [Bugfix] Update expected shape for per token strategy

.github/workflows/build.yml, .github/workflows/test.yml, .github/workflows/upload.yml
This PR updates and fixes Testmo actions/usage logic:
* All Testmo actions are updated to the latest version (which, among other things, eliminates the need to install the CLI tool separately)
* Fixes a "bug" in the conditional logic so that it is properly evaluated (it seems that GitHub doesn’t like mixing functions / expressions in and out of the double-curly braces in these places)
Here is a re-run of the upload workflow that failed on `main` (due to a Testmo step not being correctly skipped and thus failing): https://github.com/neuralmagic/compressed-tensors/actions/runs/12468376137/job/34799436033
=> Update & fix Testmo actions/logic

src/compressed_tensors/compressors/model_compressors/model_compressor.py, src/compressed_tensors/compressors/quantized_compressors/base.py, src/compressed_tensors/compressors/quantized_compressors/naive_quantized.py, src/compressed_tensors/compressors/quantized_compressors/pack_quantized.py, src/compressed_tensors/compressors/sparse_compressors/base.py, src/compressed_tensors/compressors/sparse_compressors/sparse_bitmask.py, src/compressed_tensors/quantization/lifecycle/apply.py, src/compressed_tensors/quantization/lifecycle/forward.py, src/compressed_tensors/utils/safetensors_load.py, tests/test_compressors/model_compressors/test_model_compressor.py, tests/test_compressors/sparse_compressors/test_bitmask.py, tests/test_quantization/lifecycle/test_apply.py, tests/test_utils/test_safetensors_load.py, tests/testing_utils.py
This PR enables composability in the ModelCompressor!
1. **Support for `targets` and `ignore` in SparseCompressors**  
Adds flexibility to specify layers for compression.
2. **Composability for `compress`/`decompress` pathways**  
3. **Typing updates**  
Improves type annotations for some methods.
4. **New tests**  
- **Composability Test** to validate the integration of compression features.
- **FP8 Test** to verify composability with FP8 quantization.
- Tests for expanding targets for SparseCompressors
- Adds some testing utilities as well
---
<details>
<summary>Expand to view the test script</summary>
```python
import torch
import argparse
from pathlib import Path
from transformers import AutoTokenizer, AutoModelForCausalLM, AutoConfig
from llmcompressor.transformers import oneshot …
```
=> Composability

src/compressed_tensors/compressors/model_compressors/model_compressor.py
When the sparse compressor is set to `"dense"`, sparse decompression is incorrectly triggered, causing uninitialized weights and downstream errors.  
Example CI failure: [[GitHub Actions Log](https://github.com/vllm-project/llm-compressor/actions/runs/12659596814/job/35326229412)](https://github.com/vllm-project/llm-compressor/actions/runs/12659596814/job/35326229412).
Added a condition to skip sparse decompression when the sparsity configuration format is `"dense"`.
- Verified against `llm-compressor` main commit: `03e21770`.
- Confirmed weights load correctly for dense compressors.
- All CI workflows pass without regressions.
=> Fix: Disable Sparse Decompression for Dense Compressors

tests/test_quantization/lifecycle/test_apply.py
We recently encountered a failure due to the release of Transformers 4.48. Details of the failure can be found here: [GitHub Actions Failure](https://github.com/neuralmagic/compressed-tensors/actions/runs/12711091190/job/35434507893#step:6:164).
The failure occurred because the Llama model definition in Transformers was updated to use a single rotary embedding for the model, replacing the previous implementation where there was one rotary embedding per attention block. This change was introduced in the following commit: [Transformers Commit (line 261)](https://github.com/huggingface/transformers/commit/d363e71d0e32f44d7a5b3571d4921371907bd0ee#diff-06392bad3b9e97be9ade6[…]d507c2ba1384ab872711c51L286).
Instead of relying o hardcoded values, we count the modules in question now, and check if …
=> Update: Test for Compatibility with Transformers 4.48

src/compressed_tensors/compressors/sparse_compressors/sparse_24_bitmask.py, src/compressed_tensors/utils/helpers.py
This PR fixes a missed case where shape can be a 2-D list for `Sparse24Compressor`
Tested locally with https://github.com/vllm-project/llm-compressor/pull/948
=> BugFix: Shape should be a flat list

src/compressed_tensors/quantization/quant_args.py
* Squelch warning in case where the user instantiates QuantizationArgs with dynamic quantization
```python3
from compressed_tensors.quantization import QuantizationArgs
args = QuantizationArgs(dynamic=True)
```
```
compressed_tensors/quantization/quant_args.py:226: UserWarning: No observer is used for dynamic quantization, setting to None
warnings.warn(
```
* Use `None` as observer default. In the model validator, if dynamic, observer is set to `None`. If not dynamic, None gets replaced by `minmax`
* Add help text explaining new default behavior
* Tests which use dynamic quantization such as `tests/test_quantization/lifecycle/test_dynamic_lifecycle.py::test_apply_tinyllama_dynamic_activations` now no longer raise an error
* See above test script
=> Fix warning for dynamic quantization args

src/compressed_tensors/compressors/quantized_compressors/pack_quantized.py, tests/test_compressors/quantized_compressors/test_pack_quant.py
Offset, mask operation relied on `pow` which takes time compared to bitwise operations. 
Also added tests for packed-quantized, and pseudocode on how it works
Before: 
```python3
pow(2, num_bits) // 2
```
After:
```python3
1 << (num_bits - 1)
```
=> Use faster operations on packed-quantized, add tests

.github/workflows/build.yml
This PR updates the build workflow to use Python 3.12 (and a matching updated `nm-action`) so that the tarball that gets produced will have a filename compliant with [PEP-625](https://peps.python.org/pep-0625/).
**TODO**
=> Update build workflow to Python 3.12

src/compressed_tensors/compressors/base.py, src/compressed_tensors/compressors/quantized_compressors/base.py, src/compressed_tensors/compressors/quantized_compressors/naive_quantized.py, src/compressed_tensors/compressors/quantized_compressors/pack_quantized.py, src/compressed_tensors/compressors/sparse_compressors/base.py, src/compressed_tensors/compressors/sparse_compressors/dense.py, src/compressed_tensors/compressors/sparse_compressors/sparse_24_bitmask.py, src/compressed_tensors/compressors/sparse_compressors/sparse_bitmask.py, src/compressed_tensors/compressors/sparse_quantized_compressors/marlin_24.py, src/compressed_tensors/utils/safetensors_load.py, tests/test_compressors/sparse_quantized_compressors/test_marlin_24.py
This PR **removes the class variable** `COMPRESSION_PARAM_NAMES` and replaces it with an **abstract property** `compression_param_names`, ensuring all compressors explicitly define it.  
- **Prevents Mutation** – Previously, `COMPRESSION_PARAM_NAMES` could be modified at runtime. Now, `compression_param_names` is a property, enforcing immutability.  
- **Ensures Implementation** – All subclasses **must** define `compression_param_names`, avoiding missing implementations.  
- **Improves Interoperability** – External frameworks like `huggingface/transformers` can reliably check expected parameters, especially when handling **stacked compressors**.  These framework(s) can now access a property
enforced via a contract rather than rely on a class variable which may or may not have been …
=> Replace `COMPRESSION_PARAM_NAMES` with Abstract Property

.gitignore, examples/bit_packing/ex_quantize_and_pack.py, examples/bit_packing/int4_config.json, examples/bitmask_compression.ipynb, examples/llama_1.1b/ex_config_quantization.py, examples/llama_1.1b/ex_llmcompressor_quantization.py, examples/llama_1.1b/ex_sparseml_quantization.py, examples/llama_1.1b/example_quant_config.json, examples/quantize_and_pack_int4.ipynb
After running some of the examples and discussing with Kyle, proposing some alterations to the examples provided in `compresed_tensors`. I updated the examples so that one is QDQ, one is compression using only compressed-tensors, and the last shows llm-compressor. A comment has been added at the top of each file to explain.
This refactor resolves the question around whether `freeze_module_quantization` should be moved. It's no longer needed
Other maintenance to do after merging this into Kyle's PR
- Add CI/CD to test example/notebook files as PR checks
=> Fix errors in scripts and notebooks in `examples/` and drop `sparseml` dependence

src/compressed_tensors/compressors/model_compressors/model_compressor.py, src/compressed_tensors/quantization/lifecycle/apply.py, tests/test_compressors/model_compressors/test_model_compressor.py, tests/test_quantization/lifecycle/test_apply.py
This PR introduces utility functions in `ModelCompressor` to support loading **stack-compressed models** (models with both sparsity and quantization) via Hugging Face’s `AutoModelForCausalLM`. These changes are necessary for [huggingface/transformers PR 36152](https://github.com/huggingface/transformers/pull/36152), which enables loading of stack-compressed models in the Transformers library w/o raising warnings around unexpected/missing keys.
When using `HFQuantizer`, the model graph is instantiated, and safetensor keys are validated against expected keys. Any **extra or missing keys** trigger warnings. However, due to our compression method, certain extra and missing keys are **expected**:
- **Extra keys**: Represent compression metadata stored on disk but not explicitly expected by the …
=> Add: missing and unexpected keys in ModelCompressor

.github/workflows/build-test.yml, .github/workflows/test-check.yaml, .github/workflows/trigger-all.yml
- switch h100 duo runner back to a100.
- switch ubuntu-20.04 to ubuntu-24.04 due to GH stopping to support 20.04 by April, 2025.
=> switch runners

src/compressed_tensors/linear/compressed_linear.py, src/compressed_tensors/quantization/lifecycle/initialize.py
* Support offloaded parameters when initializing KV cache parameters
* Fixes https://github.com/vllm-project/llm-compressor/issues/1192
* Replace uses of `module.register_parameter` with offloading-friendly `register_offload_parameter`
=> [Bugfix] Support offloaded parameters when initializing KV cache parameters

src/compressed_tensors/linear/compressed_linear.py
Signed-off-by: Rahul Tuli <rahul@neuralmagic.com>
For: https://github.com/neuralmagic/compressed-tensors/issues/267
Before this PR CompressedLinear would decompress the compressed weights on every forward pass. This PR adds a flag to check if weights have been decompressed, if yes then decompression is not run again.
=> Update: CompressedLinear to decompress once

src/compressed_tensors/linear/compressed_linear.py
This PR resolves the following test failure:
```
FAILED tests/lmeval/test_lmeval.py::TestLMEval::test_lm_eval - AttributeError: 'CompressedLinear' object has no attribute '_is_compressed'
```
This issue was introduced in [PR #266](https://github.com/neuralmagic/compressed-tensors/pull/266).
The `from_linear` pathway is the recommended way to use this class (this wasn't super clear), but the required `_is_compressed` attribute was added in `__init__`, leading to the failure.
- Removed the redundant `_is_compressed` variable in `__init__`, as the module's `QuantizationStatus` already provides this information.
- Added a warning for users attempting to initialize this class directly.
- The previously failing test now passes. ✅
=> [BugFix]: `AttributeError` in `CompressedLinear`

src/compressed_tensors/transforms/matrix_multiply.py, src/compressed_tensors/transforms/random_hadamard.py, src/compressed_tensors/transforms/scalar_multiply.py, src/compressed_tensors/transforms/transform_args.py, src/compressed_tensors/transforms/transform_config.py, src/compressed_tensors/transforms/transform_data.py, src/compressed_tensors/transforms/transform_scheme.py, tests/test_transforms/test_integration.py, tests/test_transforms/test_transform_args.py, tests/test_transforms/test_transform_config.py, tests/test_transforms/test_transform_scheme.py, tests/test_transforms/test_transforms.py
- Requires #264 
- Introduce Transform Args, Scheme, Config and Data as structures to define recipes to apply transforms 
- Also adds integration tests which shows the flow from recipes --> transform generation --> applying it to a model
- Define which layers should be targeted by a particular transform, as well which of the layer's parameters and/or activations 
- Details about the particular transform (type and arguments needed during initialization) 
- Includes a list of `TransformationArgs` onto which the transformation will be applied
- A dictionary of the different TransformationSchemes that should be applied to a particular model.
-  The keys can be any arbitrary string and a TransformationScheme should be provided for each new transform type.
```python
from …
```
=> [Transforms] Transform Data and Integration testing

src/compressed_tensors/linear/compressed_linear.py, tests/test_linear/__init__.py, tests/test_linear/test_compressed_linear.py
Summary
- There was a change introduced recently that assumed each CompressedLinear layer had a `weight` attribute which is not the case for our packed_quantized compressor models. When weights are packed, the weights are stored as `weight_packed` 
- As a result, the change incorrectly assumed the weight attribute always being present causing decompression failures for all W4A16 models
- Fixes this assumption and loading works correctly
Test: Added unit tests for `CompressedLinear`, that verify it's expected usage, these tests serve as quick proxies for our more extensive e2e tests in `llmcompressor`
```bash
(.venv) ➜  compressed-tensors git:(fix_compressed_linear) ✗ pytest /home/ubuntu/compressed-tensors/tests/test_linear/test_compressed_linear.py …
```
=> Fix case when using weight_packed, not weight

.github/workflows/upload.yml
Need to replace the CICD_GITHUB_PAT with a more find-grained and secure token that's only allowed for compressed-tensors and stratus repos with permissions to actions only. The new token also has a 30d life cycle to be updated.
=> use fine-grained token for workflow

src/compressed_tensors/compressors/model_compressors/model_compressor.py, src/compressed_tensors/compressors/quantized_compressors/base.py, src/compressed_tensors/compressors/sparse_quantized_compressors/marlin_24.py, tests/test_compressors/quantized_compressors/test_int_quant.py, tests/test_compressors/quantized_compressors/test_pack_quant.py
- Previously, we were not saving the zp if the values stored in the parameter were 0s (assumes symmetric quantization with this condition when it is certainly possible that we may have 0s as the zp for the asym case)
- However, this fails loading in the event that we're running asymmetric quantization (missing parameters)
- Update the condition for compression to directly check if we're running asym or sym quantization
Fixes: https://github.com/vllm-project/llm-compressor/issues/1190 and our general decompression issues with asym models 
- Validated models with existing integration in vLLM for W8A8 int8
- Validated asym models compressed can be loaded and run as expected
=> Rectify Asym Compression/Decompression Pathways

src/compressed_tensors/quantization/quant_config.py, tests/test_quantization/lifecycle/test_apply.py
- Remove calculation for compression-ratio which is long running potentially also incorrect
- If we were to fix the calculation/if it were useful to users, we could enable it again but will otherwise look into removing the field in a follow-up if it does not hurt backwards compat with vLLM (it shouldn't)
=> Remove compression_ratio calculation

.github/workflows/build-test.yml, Makefile, README.md
1. Updated Makefile based on latest build changes.
2. Updated README install command for nightly due to package name changes.
3. Allow report job to run no matter if tests passed or failed. Currently it only ran when tests passed.
=> fix a few minor issues

src/compressed_tensors/quantization/quant_scheme.py, src/compressed_tensors/quantization/utils/helpers.py
This aligns the logic for asymmetric quantization with the implementation found in AutoAWQ's [`pseudo_quantize_tensor`](https://github.com/casper-hansen/AutoAWQ/blob/23d584c25d80381671293d2f08a9fadfa5a8986a/awq/quantize/quantizer.py#L74) function. This is some core logic here so we should all make sure we're in agreement with the changes before merging in.
To be reviewed/merged in conjunction with https://github.com/vllm-project/llm-compressor/pull/1177
=> Some fixes for AWQ

src/compressed_tensors/utils/offload.py, tests/test_utils/test_offload.py
* Implement utility used by https://github.com/vllm-project/llm-compressor/pull/1263
* Nice grouping of accelerate utilities
* Implement `align_modules`, which allows for multiple modules to be onloaded/offloaded at the same time
```python3
for layer in layers:
with align_modules(layer.modules()):
layer(batch)
```
* Added test in `tests/test_utils/test_offload.py`
=> [Utils] add align_modules

src/compressed_tensors/quantization/lifecycle/initialize.py
Thanks to @kylesayrs for figuring out this root issue and fix. Here is his explanation:
`qparams` follow the offloading behavior of their weight. If the module is offloaded, we assume that it should initialize on the cpu. In reality, it's not the offload device that matters (cpu), but the execution device (gpu). It makes initialization a little bit slower, but is more technically correct (all ops should happen on execution device, including initialization).
=> Fix `_initialize_scale_zero_point` initializing on the wrong device

src/compressed_tensors/quantization/lifecycle/initialize.py, tests/test_quantization/lifecycle/test_initialize.py
* Fix shape calculation for group quantization
* This was uncovered while attempting to quantize the vision tower of qwen2.5 model. This likely went unnoticed, since most model shapes are powers of two, something that is not true of weights in the qwen 2.5 vision tower
* Use the ceil of num columns / group_size in order to reflect that the remainder columns are a group
* The test added by https://github.com/vllm-project/llm-compressor/pull/1401 fails without these changes, but succeeds with them
=> [Bugfix] Fix shape calculation for group quantization

src/compressed_tensors/compressors/model_compressors/model_compressor.py, src/compressed_tensors/compressors/quantized_compressors/base.py
* The name `weight_name` is confusing, as this value is not the name of a weight, but instead the path to a module
* Rename `weight_name` to `module_path`
* N/A: Name change only
=> Clarify decompression return type

src/compressed_tensors/utils/safetensors_load.py
* Fix unclear name as revealed by https://github.com/neuralmagic/compressed-tensors/pull/310#discussion_r2078280045
* Rename `dense_param` to `module_path` in the context of getting `nested_weight_mappings`
```python3
assert match_param_name('model.embed_tokens.weight', 'weight') == 'model.embed_tokens'
```
=> Clarify `match_param_name` return type

src/compressed_tensors/compressors/quantized_compressors/__init__.py, src/compressed_tensors/compressors/quantized_compressors/nvfp4_quantized.py, src/compressed_tensors/config/base.py, tests/test_compressors/quantized_compressors/test_nvfp4_quant.py
Summary
- Adds a `NVFP4Compressor` to compress FP4 weights into uint8
- Compatible with the ModelOpt Integration in vLLM
- Runs e2e using the FP4 CT Emulation: https://github.com/neuralmagic/vllm/pull/59
Shoutout to @mgoin for helping speed up the packing functionality
=> [Compressor][NVFP4] Support FP4 Compression

src/compressed_tensors/quantization/quant_args.py, src/compressed_tensors/quantization/quant_scheme.py
Summary
- Add NVFP4A16 scheme for weight-only NVFP4 models
- Add helpful args/data classes required for fp4, as there is not yet a dtype in torch
=> [NVFP4] Update FloatArgs and NVFP4

src/compressed_tensors/quantization/quant_args.py, src/compressed_tensors/quantization/quant_scheme.py
When looking at our usage of `pydantic.model_validator`, I noticed a couple incorrect signatures for when `mode="after"`.
=> fix signatures on model_validator functions

src/compressed_tensors/compressors/model_compressors/model_compressor.py, src/compressed_tensors/compressors/quantized_compressors/base.py, src/compressed_tensors/compressors/sparse_compressors/base.py, src/compressed_tensors/compressors/sparse_compressors/dense.py, src/compressed_tensors/compressors/sparse_compressors/sparse_24_bitmask.py, src/compressed_tensors/compressors/sparse_quantized_compressors/marlin_24.py, src/compressed_tensors/linear/compressed_linear.py, src/compressed_tensors/utils/helpers.py, src/compressed_tensors/utils/safetensors_load.py, tests/test_compressors/model_compressors/test_model_compressor.py, tests/test_compressors/sparse_compressors/test_sparse_24_bitmask.py
* Reduce memory requirements when compressing a model
<details><summary>Compression Memory Improvement</summary>
<table>
<tr>
<td>Format</td>
<td>State dict compression</td>
<td>Model compression</td>
</tr>
<tr>
<td>Quantized</td>
<td><img src="https://github.com/user-attachments/assets/da44a281-d8b5-43c7-8680-ae25423916ba"></td>
<td><img src="https://github.com/user-attachments/assets/a485a4c4-560d-40ec-8ade-ea4780f620de"></td>
</tr>
<tr>
<td>Sparse</td>
<td><img src="https://github.com/user-attachments/assets/d9828c87-c5f7-44ec-b966-4a6a225928c9"></td>
<td><img src="https://github.com/user-attachments/assets/0c3b5658-067c-497f-ae37-923d6dd04d27"></td>
</tr>
<tr>
<td>Sparse24<br>Stacked</td>
<td><img src="https://github.com/user-attachments/assets/4624975f-c16e-47ed-92b7-6fb523c8b043"></t …
=> [Performance] Add memory compression and decompression pathways

src/compressed_tensors/compressors/model_compressors/model_compressor.py
* Fix bug where models compressed using the memory compression pathway would be saved in the `frozen` status rather than the `compressed` status
* Set the compression status of the quantization config after compression
* This is equivalent to https://github.com/neuralmagic/compressed-tensors/blob/f192f68f1839e0bc93a762b95d2f737789df873a/src/compressed_tensors/compressors/model_compressors/model_compressor.py#L510-L514
=> Model Compression: Set compression status

src/compressed_tensors/compressors/quantized_compressors/base.py, src/compressed_tensors/compressors/quantized_compressors/naive_quantized.py, src/compressed_tensors/compressors/quantized_compressors/pack_quantized.py, src/compressed_tensors/quantization/lifecycle/apply.py, src/compressed_tensors/quantization/lifecycle/forward.py, src/compressed_tensors/quantization/lifecycle/initialize.py, src/compressed_tensors/quantization/quant_args.py, src/compressed_tensors/quantization/utils/helpers.py, tests/test_quantization/lifecycle/test_initialize.py, tests/test_quantization/test_utils/test_helpers.py
- Add / Apply Fp4 quantization support
- Introduce global_scale - this scale conditionally scales the quantization weight scale during run time and is saved to disk as part of the model checkpoint.
- Update quant/dequant to apply the global_scale during calibration / observer calls 
- Add additional test cases
- Tested e2e end with the llmcompressor branch which enables FP4 Quantization
=> [NVFP4] Enable Fp4 Quantization; introduce / apply global_scales

src/compressed_tensors/quantization/lifecycle/initialize.py
- Solves failing e2e nightly tests for Phi models 
- No need to recalculate the global scale if the layer is already fused
=> [NVFP4] Skip fused global scale calculation if already fused

src/compressed_tensors/quantization/quant_args.py
**Description**
This PR addresses the following [issue](https://github.com/vllm-project/llm-compressor/issues/1222). Update such that the MSE is used as the default observer as opposed to MinMax.
**Testing**
Ran `examples/quantization_w4a16` and inspected the observer. See `QuantizationArgs`:
```
weights=QuantizationArgs(num_bits=4, type='int', symmetric=True, group_size=128, strategy='group', block_structure=None, dynamic=False, actorder=None, observer='mse', observer_kwargs={})
```
More details:
**Concern**
@anmarques @eldarkurtic Wanted to reach out to confirm if this is what we wanted : )
=> Update default observer to be `MSE`

src/compressed_tensors/registry/registry.py
* Better typehinting for `RegistryMixin`
* Use generic type `T` to describe a class which inherits from `RegistryMixin`
* Replace uses of `typing.Type` with `builtins.type`, as [Type is deprecated](https://docs.python.org/3/library/typing.html#typing.Type)
=> [Misc] Generics typehinting for `RegistryMixin`

src/compressed_tensors/quantization/lifecycle/forward.py, src/compressed_tensors/quantization/lifecycle/initialize.py, src/compressed_tensors/quantization/quant_args.py, src/compressed_tensors/quantization/quant_scheme.py, src/compressed_tensors/quantization/utils/helpers.py, tests/test_quantization/lifecycle/test_initialize.py
- Adds the `NVFP4` preset scheme which has both FP4 weight quantization and input activation quantization 
- Extends the dynamic scale generation function to generate per group scales (previously only done for per-tensor, per-token strategies)
- Makes use of a new `tensor_group` strategy which is used by the activations
- The activations are generated per-group (for group_size 16) 
- The activation are dynamic 
- The activations make use of a global_scale 
- The name `tensor_group` was selected as like FP4 weight quantization, a global scale is also generated on a per tensor basis (through calibration) which is then used to scale the local quantization group scales, which are generated and applied dynamically
- We may dynamically generate the global scale in the future as a variation
- …
=> [NVFP4] Add `tensor_group` strategy; enable NVFP4 Activations

src/compressed_tensors/transform/__init__.py, src/compressed_tensors/transform/transform_args.py, src/compressed_tensors/transform/transform_config.py, src/compressed_tensors/transform/transform_scheme.py, tests/test_transform/test_transform_args.py, tests/test_transform/test_transform_config.py, tests/test_transform/test_transform_scheme.py
- Introduce Transform Args, Scheme, Config and Data as structures to define recipes to apply transforms 
- When compared to https://github.com/neuralmagic/compressed-tensors/pull/275, the requirement for `ModuleTarget`, and `TransformData` has been removed as well as the `transform_creation_args` and `call_args` fields
- Supports spinquant-like transform configs which target non-linear modules such as `q_attn` and `k_cache`
- Arguments which define how and where a transform should be applied to a model
- Scheme used to parameterize a particular transform type and specify how and where it should be applied to the model
- Includes a list of `TransformationArgs` onto which the transformation will be applied
- Configuration of transforms to be applied to a model. This config is to be …
=> [Transforms] Transform Args, Scheme, and Config

.github/workflows/build-test.yml
Use the `gcp-k8s-util` runner for the “UPLOAD” job, rather than `k8s-util`. This runner is not showing the same issues currently affecting `k8s-util`, and was able to complete the “UPLOAD” job successfully: https://github.com/neuralmagic/compressed-tensors/actions/runs/15326172818/job/43121574349
=> Use different runner for UPLOAD job

src/compressed_tensors/quantization/quant_args.py, src/compressed_tensors/quantization/utils/helpers.py
Summary
- Wrap rounding function in torch.compile - this seems to result in a 33% speed-up + seems like a good first step but I’d like to explore other bottlenecks 
- Fix typo
=> [NVFP4]  Use torch.compile when rounding to NVFP4

src/compressed_tensors/quantization/lifecycle/forward.py
Summary
- Update group quant to no longer apply the scales in a loop
- This significantly speeds up QDQ, especially in the case of fp4 where we have group sizes of size 16 
Testing
- All test cases pass
- Works e2e
=> [Quantization] Update group quantization

src/compressed_tensors/compressors/model_compressors/model_compressor.py, src/compressed_tensors/compressors/quantized_compressors/base.py
Unlike the sparse decompressor, the quantized decompressor does not yield unused parameters. Infact, the standard `decompress_from_state_dict` function cannot yield unused parameters without significantly modifying the `get_nested_mappings_from_state_dict` function. Because of this contract inflexibility and fundamental difference between the return types of sparsity decompressors and quantization decompressors, it's more conceptually simple to add a separate function `decompress_module_from_state_dict` for handling quantized decompression of module state dicts.
* Add `decompress_module_from_state_dict` which decompresses a module's static dict
* Simplify some code in `decompress_from_state_dict`
* Modify model compressor to use new `decompress_module_from_state_dict` function
* Locally …
=> [Decompression] Keep unused parameters when decompressing from memory

src/compressed_tensors/utils/offload.py
Before, if accelerate is absent, the `check_accelerate` decorator would generate an error at import time whenever `@check_accelerate(fallback="error")` is specified. After it fails only if the particular function is called.
=> Fix error on import whenever accelerate is absent

src/compressed_tensors/transform/factory/base.py
* In python3.11 a lot changed about Enum types. While the [documentation](https://docs.python.org/3/library/enum.html) doesn't explicitly state it, I've observed that casting to string via fstrings has different behavior starting in python3.11
Python3.10
```python3
>>> f"{TransformLocation.WEIGHT_INPUT}" 
'weight_input'
```
Python3.11
```python3
>>> f"{TransformLocation.WEIGHT_INPUT}"
'TransformLocation.WEIGHT_INPUT'
```
* Fix names given to transform submodules
* Use enum value property when assigning submodule names. This property is a safe representation across python versions
Python3.10
```python3
>>> f"{TransformLocation.WEIGHT_INPUT}" 
'weight_input'
```
Python3.11
```python3
>>> f"{TransformLocation.WEIGHT_INPUT}"
'weight_input'
```
=> [Transform] [Bugfix] Fix enum value serialization in python>=3.11

src/compressed_tensors/utils/offload.py, tests/test_utils/test_offload.py
* Fix offloading bug reported by @logos-mhr  https://github.com/vllm-project/llm-compressor/pull/1263#issuecomment-2962012381
Accelerate's `AlignModuleDevices` hook has a `original_devices` attribute which it uses to track the device a parameter was on before it was offloaded. That way, when the hook is removed, the parameter can be placed back on the original device it started on.
This consideration was missing from the original `register_offload_parameter` implementation. This caused newly added parameters (qparams) to stay meta device when `disable_hf_hook` was called (during the quantization wrapper).
This wasn't a problem, since they'd be re-replaced on the correct device when the hook was reapplied, but this did mean that the hook recorded the original device as "meta", hence …
=> [Accelerate] Extend functionality of `register_offload_parameter`

src/compressed_tensors/utils/offload.py
* Fix saving models which have been dispatched by `offloaded_dispatch`
* Add util to remove hooks before dispatching in order to guarantee successful dispatch
Attempting to save a model which has been dispatched by `offloaded_dispatch` will fail because HF transformers will not onload weights for saving unless it detects a `device_map` attribute. See [here](https://github.com/huggingface/transformers/blob/main/src/transformers/modeling_utils.py#L3619-L3623),  [here](https://github.com/huggingface/transformers/blob/main/src/transformers/modeling_utils.py#L3685), and [here](https://github.com/huggingface/transformers/blob/main/src/transformers/modeling_utils.py#L3814).
This change is mostly inconsequential for typical LLM Compressor examples, since offloading hooks are anyways removed …
=> [Bugfix] Fix saving of models dispatched by `offloaded_dispatch`

src/compressed_tensors/utils/offload.py, tests/test_utils/test_offload.py
* Enable model device inference https://github.com/vllm-project/llm-compressor/pull/1572
* When checking for offloading, check all submodules in the order that they're returned
* Existing tests pass
* Added model tests pass
* Deepseek tests on LLM Compressor pass
=> [Accelerate] Expand `get_execution_device` to support models

.github/actions/test/action.yml, .github/workflows/test.yml, .github/workflows/trigger-all.yml
The workaround to clean up disk space looks working and a successful run is here: https://github.com/neuralmagic/compressed-tensors/actions/runs/15982420861
The workaround is based on the proposal in this runner image repo issue: https://github.com/actions/runner-images/issues/10386.
These folders are relatively large size and unnecessary so it's safe to clean up.
=> Clean up disk space and restore ubuntu 22.04 runner

src/compressed_tensors/quantization/lifecycle/apply.py, src/compressed_tensors/transform/factory/base.py
bugfixes to get this branch to work with [kylesayrs/transform-modifier](https://github.com/vllm-project/llm-compressor/tree/kylesayrs/transform-modifier).
Currently failing on load-up in vllm:
```
Loading safetensors checkpoint shards:   0% Completed | 0/14 [00:00<?, ?it/s]
ERROR 07-01 22:26:57 [core.py:515] EngineCore failed to start.
ERROR 07-01 22:26:57 [core.py:515] Traceback (most recent call last):
ERROR 07-01 22:26:57 [core.py:515]   File "/home/bdellabe/projects/.venv/lib/python3.10/site-packages/vllm/v1/engine/core.py", line 506, in run_engine_core
ERROR 07-01 22:26:57 [core.py:515]     engine_core = EngineCoreProc(*args, **kwargs)
ERROR 07-01 22:26:57 [core.py:515]   File "/home/bdellabe/projects/.venv/lib/python3.10/site-packages/vllm/v1/engine/core.py", line 390, in __init__ …
```
=> bugfixes to `kylesayrs/transform_apply`

.github/actions/test/action.yml, .github/workflows/test.yml
These code changes allow the `test` action to toggle on collection of code coverage metrics while pytest is running.  This uses the `pytest-cov` package to collect and report the metrics.
metrics are consolidated in a compressed artifact attached to the `test` action.
metrics are reported as both a .json file and .html files.
Run of the `test` action w/ no code coverage requested, to demonstrate default behavior matches the existing behavior: https://github.com/neuralmagic/compressed-tensors/actions/runs/16126116474
Run of the `test` action w/ code coverage requested has the collected results available as an artifact at the bottom of the summary:
https://github.com/neuralmagic/compressed-tensors/actions/runs/16010001155
=> enable code coverage collection and reporting INFERENG-1049

src/compressed_tensors/compressors/model_compressors/model_compressor.py, src/compressed_tensors/quantization/lifecycle/apply.py, src/compressed_tensors/quantization/quant_config.py, src/compressed_tensors/quantization/utils/helpers.py, src/compressed_tensors/transform/factory/base.py, src/compressed_tensors/utils/__init__.py, src/compressed_tensors/utils/internal.py, src/compressed_tensors/utils/untargetable.py, tests/test_quantization/lifecycle/test_apply.py
* Refactor module targeting to be cleaner and easier to maintain
* Support skipping `TransformBase` modules
* https://github.com/vllm-project/llm-compressor/pull/1628
* Deprecated `iter_named_leaf_modules` and `iter_named_quantizable_modules`
* These functions are near copies of each other
* These functions don't actually have any runtime savings over simple `model.modules()`. Infact, they're likely significantly slower
* These functions hard code against "observer" module names and are difficult to extend to other modules like Transforms
* Add `UntargetableModule` class
```python3
class UntargetableModule(torch.nn.Module):
"""
Abstract base class for modules which are not a part of the the model definition.
`torch.nn.Module`s which inherit from this class will not be targeted by configs …
```
=> Deprecate `iter_named_leaf_modules` and `iter_named_quantizable_modules`

src/compressed_tensors/compressors/model_compressors/model_compressor.py, src/compressed_tensors/compressors/sparse_compressors/sparse_24_bitmask.py, tests/test_compressors/model_compressors/test_model_compressor.py
* Fix model device movement if the model is deployed to multiple GPUs
Getting the `type` attribute of a `torch.device` strips away the index of the device (for example, both `cuda:0` and `cuda:1` become `cuda`). This means that when the module parameters are placed back on their original `onloading_device`s, they'll all be move to `cuda:0`, even if they started on a different device. This could lead to memory issues for larger models
=> [Compression] Fix compression device movement in cases of indexed devices

.github/actions/test/action.yml, .github/workflows/build-test.yml, .github/workflows/test.yml, .github/workflows/trigger-all.yml
Code coverage is enabled for one of the nightly test jobs. Reporting will be available at the repo's GH pages here: https://neuralmagic.github.io/compressed-tensors/
A successful run from this PR is here: https://github.com/neuralmagic/compressed-tensors/actions/runs/16198607586
and the coverage results have been uploaded to the GH pages.
The GH pages is configured to only allow reports uploaded from the main branch GHA run going forward.
=> Enable code coverage report for nightly tests

src/compressed_tensors/compressors/model_compressors/model_compressor.py
* Skip compression for attention modules, which have a quantization config but do not have weights to quantize
* Without these changes, attention modules will be compressed. This is not a problem in itself (since they have no weights, they are no opped), but https://github.com/neuralmagic/compressed-tensors/pull/347 fixes a bug which occurs when non-leaf modules are attempted to be compressed
* `map_module_to_scheme` used to only quantize compress leaf modules. Now, this method only quantize compresses modules with weight quantization
* KV cache tests pass with https://github.com/vllm-project/llm-compressor/pull/1635
=> [Bugfix] Only quant-compress modules with weight quantization

src/compressed_tensors/transform/factory/base.py, src/compressed_tensors/transform/transform_args.py
* Allow transforms config to be serialized without encoding python objects
* This is specifically useful for serializing recipes
<details><summary>previous.yaml</summary>
```yaml
default_stage:
default_modifiers:
SpinQuantModifier:
rotations:
- !!python/object/apply:llmcompressor.modifiers.transform.spinquant.base.SpinquantRotation [
R1]
- !!python/object/apply:llmcompressor.modifiers.transform.spinquant.base.SpinquantRotation [
R2]
transform_type: hadamard
randomize: false
learnable: false
transform_config:
config_groups:
R1:
type: hadamard
apply:
- targets: ['re:.*embed_tokens$', 're:.*o_proj$', 're:.*down_proj$']
location: !!python/object/apply:compressed_tensors.transform.transform_args.TransformLocation [
weight_output]
inverse: false
ignore: []
- targets: ['re:.*q_proj$', …
```
=> [Transform] Fix config serialization

src/compressed_tensors/compressors/model_compressors/model_compressor.py
* Safeguard against attempts to delete submodule parameters during model decompression
* This occurs when attempting to compress attention modules, which have quantization configs and submodules
* Prior to https://github.com/neuralmagic/compressed-tensors/pull/381, this was skipped by `iter_leaf_modules`
=> [Bugfix] Safeguard against submodule parameter deletion in decompress_model

src/compressed_tensors/quantization/lifecycle/initialize.py, tests/test_quantization/lifecycle/test_initialize.py
- Fixed shape mismatch error in block quantization example
- Add block quantization shape initialization and throw a warning when users attempt to apply block quantization on activations. 
- Tested the example & `test_initialization.py` in compressed-tensors. Let me know if there's anything else I should test for.
=> fix block quantization initialization

src/compressed_tensors/quantization/lifecycle/forward.py, src/compressed_tensors/quantization/lifecycle/initialize.py, src/compressed_tensors/quantization/quant_scheme.py, src/compressed_tensors/transform/factory/hadamard.py, src/compressed_tensors/utils/match.py, tests/test_utils/test_match.py
* Allow matching utils to be used for quantization matching (and otherwise) by guarding against matching internal modules
* Do not match against modules which are internal modules
* Make `match_name` and `match_module` private functions in order to avoid them being to used to match against internal modules
* Added internal modules matching tests
=> [Utils] Skip internal modules when matching

src/compressed_tensors/compressors/quantized_compressors/nvfp4_quantized.py, src/compressed_tensors/quantization/lifecycle/forward.py, src/compressed_tensors/quantization/utils/helpers.py, tests/test_quantization/test_utils/test_helpers.py
- Add compression info for nvfp4 to support decompression with CompressedLinear
- Update to support batch_size > 1 when running QDQ for tensor_group / group dynamic activations - this is done by updatng the reshape command to be generic such that all dimensions are maintained apart from the last / group_dim which has to be reshaped for QDQ
=> [Quantization][Decompression] Fix QDQ for dynamic quant; Update NVFP4 Compression Params

src/compressed_tensors/utils/match.py, tests/test_utils/test_match.py
* Support matching vLLM modules using utilities defined by compressed tensors, as indicated by [this comment](https://github.com/vllm-project/vllm/blob/main/vllm/model_executor/layers/quantization/compressed_tensors/compressed_tensors.py#L494-L496)
* Support passing a fused modules mapping to `match_named_modules`, `match_named_parameters`, and `is_match`
* Since vLLM only matches schemes to modules (rather than the other way around), only `is_match` will be used in practice
* Support matching `Linear` to vLLM's `LinearBase`
* Regression matching tests pass
* Add tests pass
=> [Utils] Support matching vLLM modules

src/compressed_tensors/quantization/lifecycle/forward.py
The `dequantize` function incorrectly used `scale.shape` directly as `block_structure`.
Calculate actual block dimensions from tensor and scale shapes:
- Fixes garbage output in decompressed models using block quantization
- Ensures correct block structure interpretation during dequantization
=> Fix block size inference logic

src/compressed_tensors/utils/offload.py
Device type error encountered 
```
is_meta = module_device.type == "meta"
AttributeError: 'int' object has no attribute 'type'
```
Added wrapper to make sure that `get_execution_device` always returns `torch.device`. 
Tested the failed test locally. 
```
pytest tests/examples/test_quantizing_moe.py::TestQuantizingMOE::test_deepseek_example_script[mixtral_example.py]
============================================================================================= test session starts =============================================================================================
platform linux -- Python 3.10.12, pytest-8.3.5, pluggy-1.5.0
rootdir: /home/hzhao/llm-compressor
configfile: pyproject.toml
plugins: anyio-4.9.0, rerunfailures-15.0, mock-3.14.0
collected 1 item …
```
=> added wrapper for execution device

src/compressed_tensors/quantization/quant_scheme.py
- Ensure per-module quantization schemes are not created with format as `mixed-precision`
=> [QuantizationScheme] Validate format

src/compressed_tensors/utils/match.py
Fix match.py syntax for python 3.9
=> fix match.py syntax

src/compressed_tensors/utils/offload.py
* Fix bug where `remove_dispatch` would not remove dispatches from models which do not use `_hf_device_hook`s
* Consistently removed dispatches from models, even if the model was dispatched to only one GPU
* Explicitly move model to CPU when removing dispatch
Able to remove explicit device movement from https://github.com/vllm-project/llm-compressor/pull/1744
=> [Offload] Fully remove dispatch

src/compressed_tensors/compressors/model_compressors/model_compressor.py, src/compressed_tensors/quantization/lifecycle/apply.py, src/compressed_tensors/utils/match.py, tests/test_quantization/lifecycle/test_apply.py, tests/test_utils/test_match.py
=> Refactor module / parameter matching logic

src/compressed_tensors/compressors/quantized_compressors/nvfp4_quantized.py
Applies `torch.compile` to nvfp compressor as suggested in https://github.com/vllm-project/llm-compressor/issues/1485
Speed ups anywhere from 3x to 25x depending on cpu/gpu.
<details>
<summary> Benchmark pack/unpack (new) </summary>
```
./benchmark_fp4_packing.sh 
Running benchmark on CPU...
Creating tensor of shape (8192, 8192) on cpu...
Benchmarking on tensor of shape torch.Size([8192, 8192]) (67,108,864 elements) on cpu
Iter 1/3 - Pack: 1.8949s
Iter 2/3 - Pack: 0.0454s
Iter 3/3 - Pack: 0.0464s
Iter 1/3 - Unpack: 0.0784s
Iter 2/3 - Unpack: 0.0374s
Iter 3/3 - Unpack: 0.0377s
Benchmark Results:
Device: cpu
Tensor shape: 8192x8192 (67,108,864 elements)
Average pack time: 0.6622s (101.34M elements/s)
Average unpack time: 0.0512s (1311.30M elements/s)
Compression ratio: 8.00x …
```
=> Speed up nvfp4 pack/unpack w/ torch.compile

src/compressed_tensors/compressors/model_compressors/model_compressor.py, src/compressed_tensors/quantization/lifecycle/apply.py
* Simplify/ restructure `apply_quantization_config` to make subsequent steps easier to understand
* Remove return value of `apply_quantization_config` (only used in one place)
* Reorder lines without changing functionality (this makes subsequent replacements much easier to read)
=> Simplify `apply_quantization_config`

examples/llama_1.1b/ex_llmcompressor_quantization.py
Remove references to deprecated `llmcompressor.transformers.oneshot`
=> remove references to `llmcompressor.transformers.oneshot` in examples

src/compressed_tensors/utils/offload.py
* Remove unused accelerate utilities
* https://github.com/vllm-project/llm-compressor/pull/1556
* Remove `is_module_offloaded` and `update_prefix_dict`
* In the future, `update_parameter_data` can be removed as well once its uses are replaced by the new name
=> [Accelerate] Remove `is_module_offloaded` and `update_prefix_dict`

src/compressed_tensors/utils/helpers.py
* Support logging deprecation warnings only once for functions which are called many times
* Use generics type hinting
* Use `logger.bind(log_once=True).warning(message)` to log once
* Confirmed that deprecation warnings are only called once
=> [Utils] Improve type hints for `deprecated`, only log once

setup.py, src/compressed_tensors/utils/helpers.py
Resolves #468 
As described in
* #468 
`frozendict` has a license that breaks downstream allowlists, preventing some users from upgrading to current version of `compressed-tensors`. This removes that dependency, instead using `types.MappingProxyType`, a read-only view to a dictionary that is part of stdlib. `frozendict` was only used in a single file, so this ended up being a minimal change.
=> [licensing refactor] remove `frozendict` dependency, use `types.MappingProxyType` instead

src/compressed_tensors/transform/apply.py, src/compressed_tensors/transform/factory/base.py, src/compressed_tensors/transform/factory/hadamard.py, src/compressed_tensors/transform/utils/hadamard.py, tests/test_transform/conftest.py, tests/test_transform/factory/test_serialization.py
* Support applying random hadamards on meta device so that they can be loaded in HF
* https://github.com/huggingface/transformers/pull/40673
* The above PR will be able to land once this PR has been released
* https://github.com/neuralmagic/compressed-tensors/pull/444
* https://github.com/neuralmagic/compressed-tensors/pull/423
* Rename `_update_tied_weights` to `_tie_offloaded_tensors`
* The new name and comments makes its to make its purpose more clear
* Move to `apply` in order to avoid redundant work
* Make `_dynamic_tied_weights_keys` statically defined on the transform module
* This does not have any implications, as transformers does not check if the keys are strictly shared or even exist
* When fetching random hadamards, load them on the cpu, even if the device is meta
* Added …
=> [Transform] Support loading random hadamards on meta device

src/compressed_tensors/compressors/model_compressors/model_compressor.py, tests/test_compressors/model_compressors/test_model_compressor.py
- Previously removed as no longer required for latest transformers but required for lower bound support
=> Add back get unexpected keys to support transformers lower bound

src/compressed_tensors/transform/factory/hadamard.py, src/compressed_tensors/transform/factory/matrix_multiply.py, src/compressed_tensors/transform/transform_scheme.py, tests/test_transform/factory/test_correctness.py, tests/test_transform/test_transform_scheme.py
We deprecated `TransformScheme.head_dim` in favor of `block_size` in #466 , but vllm still references `head_dim` [here](https://github.com/vllm-project/vllm/blob/3468f17ebe4daf19ff120d95eebde48f59d7cac2/vllm/model_executor/layers/quantization/compressed_tensors/transform/module.py#L90). 
This PR reverts the deprecation because it is not worth the pain of resolving a name change in vllm, which would require several steps:
1. Fix CT so that head_dim can still be used, release a CT v0.12 
2. Upgrade vllm's CT dependency to v0.12
3. Then change all references of `head_dim` to `block_size` in vllm src.
4. Then we can remove the CT changes introduced in this PR
Merge in conjunction with:
* https://github.com/vllm-project/llm-compressor/pull/1870
=> [Transform] Revert deprecation of `TransformScheme.head_dim` for compatibility with vllm

.github/workflows/post-release-nightly-build.yml, .github/workflows/trigger-all.yml
Adds a new workflow that is triggered by a release event† ­­which will run the `build-test` workflow with only a single test config in order to push out a new nightly.
† The workflow uses `types: [released]`, and the `released` type, per [the docs](https://docs.github.com/en/webhooks/webhook-events-and-payloads?actionType=released#release), means:
> A release was published, or a pre-release was changed to a release.
=> [cicd] Add post-release run to push next nightly

src/compressed_tensors/quantization/utils/helpers.py
This PR fixes the activation quantization issue described in Issue #394, where the input scale shape was incorrect when using the Dynamic TOKEN strategy.
- Corrected the reduction dimensions to ensure only the hidden dimension is reduced.
- This ensures the input scale shape is `(batch_size, seq_len, 1)` instead of `(1, seq_len, hidden_dim)`.
=> [Bugfix] Fix Per-Token Dynamic Activation Quantization

src/compressed_tensors/quantization/lifecycle/initialize.py, src/compressed_tensors/quantization/utils/helpers.py
* Refactor initialize to support passing the shapes of activations
* While the true shapes of activations are determined at inference/calibration time, the last dimensions can be known from the weight
* This information is necessary to support group/head quantization, since these strategies need to know the shape of the activation at init time
* Use the module weight to infer activation and output quantization shapes
* Rename `_initialize_scale_zero_point` to `initialize_qparams`
* Introduce `strategy_cdiv` to share logic related to validating divisibility
=> [Quantization] Refactor initialize for activation shape inference

src/compressed_tensors/quantization/quant_args.py, tests/test_quantization/test_utils/test_helpers.py
* Give user errors which require that block strategy and structure are both specified
=> Add block strategy and structure validation
