src/sparsetensors/quantization/lifecycle/forward.py

gradients shouldn't be computed for Q/DQ in QAT

decorate fake quant with torch.no_grad

---

LICENSE
setup.py

Adds license and details to the final package

Final details for package

---

src/compressed_tensors/quantization/lifecycle/apply.py

- Update the match conditions between layers and values defined in target/ignore
- Make the function public for vllm use
- Ran tests under `quantization` which all pass

Update target match conditions; make public

---

src/compressed_tensors/quantization/lifecycle/apply.py

We need to initialize the zp to the correct shape when reloading from file

Additional Symmetric ZP Fix

---

src/compressed_tensors/quantization/lifecycle/apply.py

Make ZP int8 instead of int64

---

src/compressed_tensors/quantization/quant_scheme.py

Needed for https://github.com/neuralmagic/sparseml/pull/2287

Add a function to check if a string is a preset scheme

---

src/compressed_tensors/compressors/int_quantized.py
src/compressed_tensors/compressors/pack_quantized.py
tests/test_utils/test_helpers.py

3.8 has no removesuffix function, replacing with an equivalent

Fix Python 3.8 Compatability

---

setup.py

remove pydantic version cap

---

src/compressed_tensors/compressors/marlin_24.py
src/compressed_tensors/quantization/quant_args.py

Main Changes are in the SparseML PR: https://github.com/neuralmagic/sparseml/pull/2327

Fix GPTQ Aliases

---

src/compressed_tensors/quantization/lifecycle/calibration.py

Fix bug where a warning was raised

Warning Raise Bugfix

---

src/compressed_tensors/compressors/model_compressor.py

Fix for 
https://github.com/vllm-project/llm-compressor/actions/runs/10527091337/job/29169465747#step:11:133

LLM compressor GHA fix

---

src/compressed_tensors/quantization/quant_args.py
tests/test_quantization/test_quant_args.py

* Support intuitive use of the actorder quantization argument, similar to AutoGPTQ
* True defaults to group, False defaults to None
* Added tests

Support bool arguments for actorder

---

src/compressed_tensors/quantization/quant_args.py
src/compressed_tensors/quantization/quant_scheme.py
tests/test_compressors/test_fp8_quant.py
tests/test_compressors/test_int_quant.py
tests/test_quantization/test_quant_args.py

* Better UX for invalid configs
* Raise error if group_size is passed but strategy != group
* Fix tests with invalid configs

Raise error if group_size is passed but wrong strategy

---

src/compressed_tensors/version.py

bump up main to 0.6.0

---

src/compressed_tensors/quantization/quant_scheme.py
tests/test_quantization/test_quant_scheme.py

Update defaults for `QuantizationScheme` to be None

Update `QuantizationScheme` defaults

---

.github/workflows/build-test.yml
.github/workflows/build.yml
.github/workflows/trigger-all.yml

Still build/test nightly and push out to pypi for compressed-tensors.

Bring nightly build/test back

---

src/compressed_tensors/config/base.py
tests/test_configs/__init__.py
tests/test_configs/test_base.py

This PR adds a SparsityStructure Enum, as requested during PR reviews in https://github.com/vllm-project/llm-compressor/pull/822/files

Add sparsity structure enum

---

src/compressed_tensors/version.py

Bump version to v0.8.0

---

src/compressed_tensors/quantization/quant_args.py
src/compressed_tensors/quantization/quant_scheme.py
src/compressed_tensors/utils/helpers.py
tests/test_quantization/test_quant_args.py

This reverts commit 724d5cedc53097107eca104a4db698df56f85858.

Revert "Implement aliasable mixin and alias activation ordering (#213)"

---

.github/workflows/trigger-all.yml

Temporarily switching test runners from a100 to h100 to get release going.

switch runners from a100 to h100 for now

---

src/compressed_tensors/version.py

This PR bumps current compressed tesnors version for a new release

Bump: Compressed Tensors version for release

---

.github/workflows/build-test.yml
.github/workflows/build.yml
.github/workflows/test.yml
.github/workflows/upload.yml

Remove testmo related steps and actions, pending https://github.com/neuralmagic/nm-actions/pull/45, will tag nm-actions once the PR lands and update here to use the new tag.

remove testmo

---

.github/workflows/upload.yml
Makefile

- Fixed an upload issue when the package already existed on PyPI.
- Minor fix for the Makefile so "make build" command can work as expected.

Fix upload issue when package already existed on PyPI

---

.github/workflows/build.yml
.github/workflows/upload.yml

Updated action tags which fixed the pypi upload issue and added checks for generated wheel.

Update action tags

---

.github/workflows/upload.yml

Pick up a quick fix from nm-actions.
Ran workflow and verified.

Pick up fix from nm-actions

---

.github/workflows/build.yml
.github/workflows/test-check.yaml
pyproject.toml
setup.py

Update the build system configuration to consolidate the configuration for `setuptools-scm` into `setup.py` and use a newer version of the `build-ml-whl` nm-action.
Also, make some updates to the `test-check` workflow:
* fetch full git history/tags so the source install gets a proper dev version
* update the versions of `actions/checkout`/`actions/setup-python` to be current
* drop some steps that created a virtual environment that was never used
**TEST PLAN**
The actions that run on this PR will use the updated build action/configs and, in the logs for the build step during the test action, the version for the source install of `compressed-tensors` will be a proper dev version (e.g., something like `0.9.5.dev5+g58a9981`).

Updates to build system

---

src/compressed_tensors/compressors/quantized_compressors/modelopt_quantized.py

Much faster impl now that uses torch to run on CPU or GPU. We can make it faster by adding `@torch.compile`
```
python benchmark_modelopt_quant.py      
Creating tensor of shape (8192, 8192) on cpu...
Benchmarking on tensor of shape torch.Size([8192, 8192]) (67,108,864 elements) on cpu
Iter 1/3 - Pack: 1.8838s
Iter 2/3 - Pack: 1.9518s
Iter 3/3 - Pack: 1.9156s
Iter 1/3 - Unpack: 0.1986s
Iter 2/3 - Unpack: 0.2034s
Iter 3/3 - Unpack: 0.2029s
Benchmark Results:
Device: cpu
Tensor shape: 8192x8192 (67,108,864 elements)
Average pack time: 1.9171s (35.01M elements/s)
Average unpack time: 0.2016s (332.83M elements/s)
Compression ratio: 8.00x
```
```
python benchmark_modelopt_quant.py --gpu
Creating tensor of shape (8192, 8192) on cuda...
Benchmarking on tensor of shape torch.Size([8192, 8192]) …
```

Optimize pack_fp4_to_uint8 for fp4

---

src/compressed_tensors/quantization/quant_args.py

This reverts commit 89164114bfd9db90cf6abc75cdb116e701a02389.

Revert "Update default observer to be `MSE` (#300)"

---

tests/test_compressors/quantized_compressors/test_fp8_quant.py

[Tests] Update test_fp8_quant.py

---

src/compressed_tensors/quantization/lifecycle/forward.py
src/compressed_tensors/quantization/utils/helpers.py
tests/test_quantization/test_utils/test_helpers.py

Summary
- Update global_scale check
- Make global_scale have a shape 
- Add a ToDo comment for MoEs

[NVFP4] Small Nits

---

tests/test_transform/conftest.py
tests/test_transform/factory/test_correctness.py
tests/test_transform/factory/test_memory.py

* Increase reusability of transforms testing code by using pytest fixtures
* Create fixture for `TransformableModel`
* Create fixture for `model_apply`
* Tests continue to pass

[Transform] Update tests to use conftest file

---

src/compressed_tensors/compressors/model_compressors/model_compressor.py
src/compressed_tensors/quantization/lifecycle/apply.py
src/compressed_tensors/utils/match.py
tests/test_quantization/lifecycle/test_apply.py
tests/test_utils/test_match.py

This reverts commit d99d38bded141c324da4b87ebc79413fd6bc741e while LC is being released

Revert "Refactor module / parameter matching logic (#406)"
